### ISSUE TITLE
Calling @obs1dium

### ISSUE THREAD

**Issue by simplecam** [obs1dium/BetterManual#13]
Hi Obs1dium,
Apologies for re-purposing Github's 'issues' tab as a general messaging platform but I'm really keen to get in touch.
I'm not a programmer but I am commissioning some work that will make use of OpenMemoriesFramewok and is related to BetterManual. I'd love to talk/skype with you about your experiences with BetterManual. And maybe the job opening we have is something you'd be interested in.
https://unicornhunt.io/jobs/senior-mobile-developer-at-expodo
Best wishes,
Tim
[tim -at- expodo -dot- co -dot- uk]

**Comment by obs1dium** [comment]
I'll shoot you a mail later.
