### ISSUE TITLE
Sony a5100 and Better Manual application

### ISSUE THREAD

**Issue by schmety** [obs1dium/BetterManual#14]
Hi there !
I'm using your application quite some time now, 
it's very easy and clean to work with.
What i have noticed some time ago and recently, that if i set shutter speed for example 20-30 seconds i can only choose then 3-5 pictures at time.
I remember before, i was able to choose whatever i want, from 5, 7, 9 .... unlimited pictures when shooting.
Also, time to time, when i choose longer shutter speed application restarts.
I have already un-installed and installed application back and again if i want to shoot night photos and set shutter arround 15-30 seconds i can choose just 3-5 pictures at time.
Should i try anything else ?
Thanks, 
Best

**Comment by obs1dium** [comment]
When doing timelapses? The picture count does not depend on any camera settings.

**Comment by schmety** [comment]
Yes.
I use this option mainly for taking night photos.
So before 5 seconds counting i can choose how many pictures i want to shoot.
3, 5, 7, 9, ... unlimited.
But if i have shutter speed from 15-30 seconds i can select just 3 or 5 pictures, if i lowered shutter , let me say 1/50, 1/100 i can select higher value of pictures, for example to 23 pictures, but i don't see unlimited pictures option anymore.

**Comment by schmety** [comment]
Thanks for your reply.
I see.
So, if i want to shoot just photos i have 3 picture max in one shooting ?
For example, i want to shoot night photo and want to make 10 photos and then stack them.

**Comment by obs1dium** [comment]
Maybe you're selecting bracketing by mistake (lowest icon on the left)?

**Comment by schmety** [comment]
Yes, but if i remember i was able to choose whatever amount of pictures i want.
Now i can see for slower shutter speed just 3 to 5 pictures.
Bracketing is shooting in different shutter speed, right ?
Must check again when i'll have time.

**Comment by obs1dium** [comment]
Bracketing in the app works by changing shutter speed, you need to set it accordingly.

**Comment by schmety** [comment]
Thanks for your answers, i will check again, what i was doing wrong :)
