### ISSUE TITLE
BetterManual

### ISSUE THREAD

**Issue by schmety** [obs1dium/BetterManual#15]
Soon, i'll purchase full spectrum converted sony a5000 for night and IR photo.
I really like to also use BetterManual application, it's simply the best.
Does this app should work on a5000 and bulb mode ?
Thanks for any information, 
Best, 
Matej

**Comment by obs1dium** [comment]
I'm guessing it should work in principle, but I can't test it. Just give it a try and report back.

**Comment by schmety** [comment]
Great, i will test it and we'll see, thanks

**Comment by schmety** [comment]
I can confirm that BetterManaul app work at Sony a5000 model.
Best

**Comment by schmety** [comment]
Should in principle Better Manual application also work with sony a6000 , like so far at a5000 and a5100, which i have tested so far ?

**Comment by obs1dium** [comment]
The app should work on the a6000 as well.

**Comment by schmety** [comment]
Cool, will test it out next week.

**Comment by schmety** [comment]
I have tested Sony a6000 with Better Manual application. Everything works well, just i guess there's no option to use the zoom lever to activate focus magnification and zoom in or out, like on Sony a5100 or a5000 with zoom toggle button.

**Comment by obs1dium** [comment]
Yeah, I hardly ever use it for manual shooting on the a6000 since that camera has a custom button I can use for focus magnification and also lacks the touch screen.

**Comment by schmety** [comment]
Thanks for your answer. Sony a5000 also doesn't have touch screen, but it's
ok, since i use that camera for night shooting. So, i cannot use zoom
toggle option at a6000 or any other workarround ? Maybe external option ?
Would be really nice to use Better Manual at a6000, with zoom magnifier
option :-)

**Comment by schmety** [comment]
Sorry, i didn't understand you right. Is it possible to use focus magnification in Better Manual with a6000 or no ? I try to use custom buttons option for focus magnification, but didn't work in Better Manual.

**Comment by schmety** [comment]
It's ok, i found also version for a6000 model, so there's focus magnification working !
I have now Better Manual on all my cameras installed and it's the best application for far !
