### ISSUE TITLE
More exposure times to shoot

### ISSUE THREAD

**Issue by PiotrStudio** [obs1dium/BetterManual#19]
Hi, I use Sony Alpha 5000 for astrophotography. In bulb mode it exhibits strong stareater (even when bulb lasts only 15s), but with 30s built-in intervalometer it doesn't have stareater. I was wondering if it could be possible to add e.g 60s, 90s, 120s, 180s, 240s exposure times. It would be great for astrophotography not only for a5000, but also for a6000 and a7 as far as I remember.

**Comment by obs1dium** [comment]
As far as I can tell that is not possible, unfortunately.
