### ISSUE TITLE
Renders A6000 unusable

### ISSUE THREAD

**Issue by Roxxor91** [obs1dium/BetterManual#2]
Hi!
I installed and started your app and experience a severe issue now!
After starting the app and trying to change some settings, the camera started just showing the preview. No buttons react anymore, not even the on/off switch. I had to remove the battery. When I reinsert the battery again, nothing changed/still the same issue.

I right now have an unusable camera, and I hope that after some time(this night) without battery it will hopefully start working again!

Would be nice if you could have a look at this issue + some tips.
[BMANUAL.TXT](https://github.com/obs1dium/BetterManual/files/364866/BMANUAL.TXT)

**Comment by Roxxor91** [comment]
Ok. A LONG press on trash got me free again. But that was scary :/

**Comment by lh8511** [comment]
@obsidium:
I can confirm the same behavior on nex6 since v1.1.. version 1.2 also hás this issue.
 The 1.0 version worked fine and an adapted by me version of yours 1.1 works too, but yet did not figure what is the issue.
Tomorrow will compare the versions to figure out.

**Comment by obs1dium** [comment]
Apps can lock up the camera, but I don't think they can cause actual, lasting damage.
Weird that your A6000 doesn't support the auto power off function. Which firmware version are you using?

**Comment by obs1dium** [comment]
Please give version 1.3 a try.
