### ISSUE TITLE
Possibility of overcoming 30 second limit in timelapse mode, other than bulb?

### ISSUE THREAD

**Issue by ykim8** [obs1dium/BetterManual#4]
I just installed this app on a7 and it works great as intended. Thanks for doing this! 

One question - is it technically feasible to add a new shutter speed setting that exceeds 30 seconds (say, 2/5/10 minutes)? Currently there is no software solution (even connecting to PC) that would allow for automated timelapse for shutter speeds of over 30 seconds. 

There is a large group of astrophotography folks that would absolutely love this feature, if it were possible. 
: )

**Comment by jbieler** [comment]
I'm pretty sure qDslrDashboard can shoot all possible shutterspeeds with Sony cameras. So, yes it would be possible to create a long exposure app. But the easiest option would be to try qDslrDashboard (I think the computer version is even free)

**Comment by obs1dium** [comment]
I suppose it is possible, but internally it'd have to use bulb mode.

**Comment by ykim8** [comment]
I tried qDslrDashboard and it allows for interval shooting with configurable bulb time. Thanks jbieler!
