### ISSUE TITLE
Long Exposure Noise Reduction

### ISSUE THREAD

**Issue by JulioCVM** [obs1dium/BetterManual#7]
Hi @obs1dium!
First of all, thank u for the great app!!
I use it in a5000 and all I have to say is that it has saved my night timelapses because of the Long Exposure Noise Reduction disablement. 
But now I'm searching the way to apply this to the Backup.bin file to get this disablement globally in my a5000, so I can forget about this annoying feature that Sony genius engineers have enabled for us.
I would love if you could show me the way you have applied this disablement so that I can search the way of applying it to the whole firmware.

Thank you so much.

**Comment by obs1dium** [comment]
Sorry, I can't help you with that. Is has been requested already at https://github.com/ma1co/OpenMemories-Tweak/
