### ISSUE TITLE
Will NOT Exit

### ISSUE THREAD

**Issue by MikeShonk** [obs1dium/BetterManual#9]
I have a Sony A6300 and I understand the "Menu" button should exit the app but it DOES NOT.  I can't get out of the BetterManual application.  Need some help! 

Thanks!

**Comment by obs1dium** [comment]
>Exit the app using the help/trash button.

**Comment by MikeShonk** [comment]
NICE WORK!  Thanks so much.  F’n awesome ☺

**Comment by mailinglists35** [comment]
>Exit the app using the help/trash button.

this has no effect on a6500, not even powering off the camera! not even removing the battery. please help!

installed using https://github.com/ma1co/Sony-PMCA-RE

**Comment by mailinglists35** [comment]
update: exited via trash but only after removing the battery
